# Generated by Django 4.0.2 on 2022-02-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sphone',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sroll',
            field=models.IntegerField(max_length=2, unique=True),
        ),
    ]
