# Generated by Django 4.0.2 on 2022-02-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_alter_student_sclass_alter_student_ssection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sclass',
            field=models.CharField(max_length=4),
        ),
    ]
