# Generated by Django 4.0.2 on 2022-02-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_alter_student_sabsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sabsent',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
