# Generated by Django 4.0.2 on 2022-02-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pmadress',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='pradress',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='sroll',
            field=models.IntegerField(unique=True),
        ),
    ]
